name: compound-interest-api
version: 1.0.0
synopsis: API REST para cálculo de juros compostos
author: Seu Nome
maintainer: seu-email@example.com
license: MIT

dependencies:
- base >= 4.7 && < 5
- scotty >= 0.12
- aeson >= 2.0
- wai-cors >= 0.2
- wai >= 3.2
- text >= 1.2

executables:
  compound-interest-api-exe:
    main: Main.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N